const symbolGroups = [
    // ['BTCUSDT_PERP.A'],
['BTCUSDT_PERP.A,ETHUSDT_PERP.A,BNBUSDT_PERP.A,SOLUSDT_PERP.A,XRPUSDT_PERP.A,DOGEUSDT_PERP.A,ADAUSDT_PERP.A,AVAXUSDT_PERP.A,LINKUSDT_PERP.A,LTCUSDT_PERP.A,BCHUSDT_PERP.A,ETCUSDT_PERP.A,TRXUSDT_PERP.A,DOTUSDT_PERP.A,MATICUSDT_PERP.A,TONUSDT_PERP.A,SHIBUSDT_PERP.A,UNIUSDT_PERP.A,ATOMUSDT_PERP.A,XLMUSDT_PERP.A'],
['APTUSDT_PERP.A,SUIUSDT_PERP.A,SEIUSDT_PERP.A,NEARUSDT_PERP.A,FILUSDT_PERP.A,ICPUSDT_PERP.A,INJUSDT_PERP.A,TIAUSDT_PERP.A,STXUSDT_PERP.A,ARBUSDT_PERP.A,OPUSDT_PERP.A,STRKUSDT_PERP.A,ZKUSDT_PERP.A,IMXUSDT_PERP.A,RNDRUSDT_PERP.A,FETUSDT_PERP.A,WLDUSDT_PERP.A,TAOUSDT_PERP.A,PEPEUSDT_PERP.A,1000PEPEUSDT_PERP.A'],
['FLOKIUSDT_PERP.A,WIFUSDT_PERP.A,BONKUSDT_PERP.A,BOMEUSDT_PERP.A,NOTUSDT_PERP.A,MEWUSDT_PERP.A,POPCATUSDT_PERP.A,BRETTUSDT_PERP.A,TURBOUSDT_PERP.A,GALAUSDT_PERP.A,SANDUSDT_PERP.A,MANAUSDT_PERP.A,AXSUSDT_PERP.A,APEUSDT_PERP.A,BLURUSDT_PERP.A,CHZUSDT_PERP.A,GMTUSDT_PERP.A,DYDXUSDT_PERP.A,RUNEUSDT_PERP.A,AAVEUSDT_PERP.A'],
['COMPUSDT_PERP.A,MKRUSDT_PERP.A,CRVUSDT_PERP.A,LDOUSDT_PERP.A,SNXUSDT_PERP.A,SUSHIUSDT_PERP.A,YFIUSDT_PERP.A,1INCHUSDT_PERP.A,BALUSDT_PERP.A,ENSUSDT_PERP.A,PENDLEUSDT_PERP.A,JUPUSDT_PERP.A,PYTHUSDT_PERP.A,JTOUSDT_PERP.A,ALTUSDT_PERP.A,PORTALUSDT_PERP.A,AEVOUSDT_PERP.A,OMNIUSDT_PERP.A,REZUSDT_PERP.A,BBUSDT_PERP.A'],
['LISTAUSDT_PERP.A,ZROUSDT_PERP.A,ENAUSDT_PERP.A,ETHFIUSDT_PERP.A,ARKMUSDT_PERP.A,AIUSDT_PERP.A,BANANAUSDT_PERP.A,MEMEUSDT_PERP.A,ORDIUSDT_PERP.A,SATSUSDT_PERP.A,1000SATSUSDT_PERP.A,CYBERUSDT_PERP.A,PIXELUSDT_PERP.A,NFPUSDT_PERP.A,ACEUSDT_PERP.A,XAIUSDT_PERP.A,MANTAUSDT_PERP.A,RONINUSDT_PERP.A,BEAMXUSDT_PERP.A,SUPERUSDT_PERP.A'],
];





module.exports = symbolGroups;

